name: Deploy to GitHub Pages

on:
   push:
      branches: ["main"]
   schedule:
      - cron: "0 * * * *"

permissions:
   contents: read
   pages: write
   id-token: write

concurrency:
   group: "pages"
   cancel-in-progress: false

jobs:
   deploy:
      environment:
         name: github-pages
         url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Check index.hbs content
           run: cat ./src/index.hbs

         - name: Create .env file
           run: |
              echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
              echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
              echo "REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}" >> .env

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: 20

         - name: Install dependencies and build
           run: |
              npm install
              npm run build

         - name: Setup Pages
           uses: actions/configure-pages@v5

         - name: Upload artifact
           uses: actions/upload-pages-artifact@v3
           with:
              path: "dist"

         - name: Deploy to GitHub Pages
           id: deployment
           uses: actions/deploy-pages@v4
